name: Build Custom Version

on: 
  workflow_dispatch:
    inputs:
      modules:
        description: 'Space-separated list of modules to keep (e.g., holylib gameevent)'
        required: true
        type: string
      custom_vphysics:
        description: 'Include custom vphysics build'
        required: false
        default: false
        type: boolean

env:
  MODULES_LIST: "autorefresh holylib gameevent serverplugin sourcetv stringtable precachefix pvs surffix filesystem util concommand vprof cvars bitbuf networking steamworks pas bass systimer voicechat physenv net entitylist httpserver gameserver soundscape luajit holylua"

jobs:
  build_custom_version:
    runs-on: ubuntu-latest
    outputs:
      COMMAND: ${{ steps.construct_command.outputs.COMMAND }}

    steps:
      - name: Construct the removal command and output it
        id: construct_command
        run: |
          MODULES_SELECTED=(${{ inputs.modules }})

          COMMAND="${{ inputs.custom_vphysics == false && 'rm -rf source/ivp &&' || '' }} cd source/modules && ls | grep -vF -e 'none'"

          for MODULE in "${MODULES_SELECTED[@]}"; do
            if [[ " $MODULES_LIST " =~ " $MODULE " ]]; then
              COMMAND="$COMMAND -e $MODULE.cpp"
            fi
          done

          COMMAND="$COMMAND | xargs rm -f -- && cd ../../"

          echo "Generated Command: $COMMAND"
          echo "::set-output name=COMMAND::$COMMAND"

  build_holylib:
    needs: build_custom_version
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "holylib"
      BUILD_64x: "true"
      REALM: "sv"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "false"
      ARTIFACT_EXPIRE: "7"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
      ADDITIONAL_DATA: "1"
      ADDITIONAL_LINUX_32_SETUP: ${{ needs.build_custom_version.outputs.COMMAND }}
      ADDITIONAL_LINUX_64_SETUP: ${{ needs.build_custom_version.outputs.COMMAND }}

  build_ghostinj:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_PATH: "ghostinj-dll/"
      PROJECT_NAME: "ghostinj"
      BUILD_64x: "true"
      LINUX_FILEEXTENTION: "dll"
      BUILD_WINDOWS: "false"
      USE_PREFIX: "false"
      ARTIFACT_EXPIRE: "7"
      ADDITIONAL_DATA: "1"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-7"
      SOURCESDK_MINIMAL_64XBRANCH: "x86-64-patch-3"
      GARRYSMOD_COMMON: "RaphaelIT7/garrysmod_common"
